blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Ask a question
    url:  https://github.com/Pipelex/pipelex/discussions
    about: "Please start a Discussion instead of filing a blank issue."
